# Generated by Django 5.0 on 2025-05-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0003_passwordresetotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentissue",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("resolved", "Resolved")],
                default="active",
                max_length=50,
            ),
        ),
    ]
